
package client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorService", targetNamespace = "http://soap.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addition", targetNamespace = "http://soap.example.com/", className = "client.Addition")
    @ResponseWrapper(localName = "additionResponse", targetNamespace = "http://soap.example.com/", className = "client.AdditionResponse")
    @Action(input = "http://soap.example.com/CalculatorService/additionRequest", output = "http://soap.example.com/CalculatorService/additionResponse")
    public int addition(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "division", targetNamespace = "http://soap.example.com/", className = "client.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://soap.example.com/", className = "client.DivisionResponse")
    @Action(input = "http://soap.example.com/CalculatorService/divisionRequest", output = "http://soap.example.com/CalculatorService/divisionResponse")
    public int division(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiplication", targetNamespace = "http://soap.example.com/", className = "client.Multiplication")
    @ResponseWrapper(localName = "multiplicationResponse", targetNamespace = "http://soap.example.com/", className = "client.MultiplicationResponse")
    @Action(input = "http://soap.example.com/CalculatorService/multiplicationRequest", output = "http://soap.example.com/CalculatorService/multiplicationResponse")
    public int multiplication(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtraction", targetNamespace = "http://soap.example.com/", className = "client.Subtraction")
    @ResponseWrapper(localName = "subtractionResponse", targetNamespace = "http://soap.example.com/", className = "client.SubtractionResponse")
    @Action(input = "http://soap.example.com/CalculatorService/subtractionRequest", output = "http://soap.example.com/CalculatorService/subtractionResponse")
    public int subtraction(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
